# yamllint configuration for GitHub Actions workflows
# Optimized for workflow readability while maintaining strict standards

extends: default

rules:
  # Allow longer lines for GitHub Actions (URLs, long commands)
  line-length:
    max: 100
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # GitHub Actions workflows commonly use "on" which triggers truthy warnings
  truthy:
    allowed-values: ['true', 'false', 'on']

  # Allow more flexibility with comments in workflows
  comments:
    min-spaces-from-content: 1

  # Allow trailing spaces in multiline strings (common in shell scripts)
  trailing-spaces: enable

  # Allow empty lines at end of file
  empty-lines:
    max-end: 1

  # Workflow files can have deeper indentation for readability
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Allow longer document start/end markers
  document-start: disable
  document-end: disable

  # Brackets spacing for GitHub Actions expressions
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

# Only lint workflow files and other YAML configs
ignore: |
  *.md
  *.txt
  *.rb
  node_modules/
  .git/
