name: Test and merge bump PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  test-and-merge:
    if: startsWith(github.head_ref, 'bump-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: Homebrew/actions/setup-homebrew@main
      - run: |
          brew test-bot --tap sheurich/tap
          gh pr merge ${{ github.event.pull_request.number }} --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
