name: Test and merge bump PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    if: startsWith(github.head_ref, 'bump-')
    runs-on: ubuntu-latest
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_ANALYTICS: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Determine changed formulae
        id: formulae
        run: |
          set -euo pipefail

          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"

          FORMULAE=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA" -- 'Formula/*.rb' \
            | sed -e 's#^Formula/##' -e 's#\.rb$##' \
            | sort -u)

          if [[ -z "$FORMULAE" ]]; then
            echo "No formula changes detected in this PR."
            echo "has_formula=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          {
            echo "formulae<<EOF"
            echo "$FORMULAE"
            echo "EOF"
            echo "has_formula=true"
          } >> "$GITHUB_OUTPUT"

      - name: Run brew style and audit
        if: steps.formulae.outputs.has_formula == 'true'
        env:
          FORMULAE: ${{ steps.formulae.outputs.formulae }}
        run: |
          set -euo pipefail

          while IFS= read -r formula; do
            file="Formula/${formula}.rb"
            echo "Running style and audit checks for ${file}"
            brew style "$file"
            brew audit --strict --online "$file"
          done <<<"$FORMULAE"

      - name: Build and test formulae
        if: steps.formulae.outputs.has_formula == 'true'
        env:
          FORMULAE: ${{ steps.formulae.outputs.formulae }}
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        run: |
          set -euo pipefail

          while IFS= read -r formula; do
            full="sheurich/tap/${formula}"
            echo "Installing ${full}"
            brew install --build-from-source "$full"
            echo "Testing ${full}"
            brew test "$full"
            echo "Uninstalling ${full}"
            brew uninstall "$full"
          done <<<"$FORMULAE"

      - name: Merge pull request
        if: steps.formulae.outputs.has_formula == 'true'
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: |
          set -euo pipefail

          gh pr merge "${{ github.event.pull_request.number }}" --squash --delete-branch
