# .github/workflows/auto-merge-bump-pr.yml
# Automatically validate and merge bump PRs. Runs unattended.
# Validates only bump-* branches created by the bump action.

---
name: Validate and Auto-Merge Bump PR (Dynamic)

'on':
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: auto-merge-bump-pr-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  validate-and-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    # Only for bump-* branches (safer unattended automation)
    if: startsWith(github.head_ref, 'bump-')

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems (if cache miss)
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Determine formula name
        id: formula_info
        env:
          PR_HEAD_REF: ${{ github.head_ref }}
        run: |
          # Derive names safely, quoting all variables to avoid word splitting/globbing
          FORMULA_SIMPLE_NAME="$(printf '%s' "$PR_HEAD_REF" | sed -E 's/^bump-([^-]+)-.*/\1/')"
          TAP_NAME="sheurich/tap"
          FORMULA_FULL_NAME="$TAP_NAME/$FORMULA_SIMPLE_NAME"
          {
            printf 'formula_simple_name=%s\n' "$FORMULA_SIMPLE_NAME"
            printf 'formula_full_name=%s\n' "$FORMULA_FULL_NAME"
            printf 'tap_name=%s\n' "$TAP_NAME"
          } >> "$GITHUB_OUTPUT"

      - name: Run brew style
        env:
          FORMULA_PATH: "Formula/${{ steps.formula_info.outputs.formula_simple_name }}.rb"
        run: |
          echo "Running style for: $FORMULA_PATH"
          brew style "$FORMULA_PATH"

      - name: Run brew audit
        env:
          FORMULA_PATH: "Formula/${{ steps.formula_info.outputs.formula_simple_name }}.rb"
        run: |
          echo "Auditing: $FORMULA_PATH"
          brew audit --online "$FORMULA_PATH"

      - name: Run brew install and test
        env:
          FORMULA_PATH: "Formula/${{ steps.formula_info.outputs.formula_simple_name }}.rb"
        run: |
          echo "Installing from source: $FORMULA_PATH"
          brew install --build-from-source "$FORMULA_PATH"
          echo "Testing formula: $FORMULA_PATH"
          brew test "$FORMULA_PATH"
          echo "Uninstalling formula: $FORMULA_PATH"
          brew uninstall "$FORMULA_PATH"

      - name: Auto-merge PR
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          echo "Attempting to merge PR #${PR_NUMBER} for branch: ${PR_BRANCH}"
          # Respect checks; do not override protections. Remove --admin.
          if gh pr merge "$PR_NUMBER" --squash --delete-branch; then
            echo "Successfully merged PR #${PR_NUMBER} and deleted branch: ${PR_BRANCH}"
          else
            echo "Failed to merge PR #${PR_NUMBER} for branch: ${PR_BRANCH}"
            exit 1
          fi
