# .github/workflows/auto-merge-bump-pr.yml
# Automatically validate and merge bump PRs. Runs unattended.
# Validates only bump-* branches created by the bump action.

---
name: Validate and Auto-Merge Bump PR (Dynamic)

'on':
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: auto-merge-bump-pr-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  validate-and-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    # Only for bump-* branches (safer unattended automation)
    if: startsWith(github.head_ref, 'bump-')

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems (if cache miss)
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Determine formula name
        id: formula_info
        run: |
          FORMULA_SIMPLE_NAME=$(echo "${{ github.head_ref }}" | sed -E 's/^bump-([^-]+)-.*/\1/')
          TAP_NAME="sheurich/tap"
          FORMULA_FULL_NAME="$TAP_NAME/$FORMULA_SIMPLE_NAME"
          echo "formula_simple_name=$FORMULA_SIMPLE_NAME" >> $GITHUB_OUTPUT
          echo "formula_full_name=$FORMULA_FULL_NAME" >> $GITHUB_OUTPUT
          echo "tap_name=$TAP_NAME" >> $GITHUB_OUTPUT

      - name: Run brew style
        run: |
          FORMULA_FULL_NAME="${{ steps.formula_info.outputs.formula_full_name }}"
          echo "Running style for: $FORMULA_FULL_NAME"
          brew style "$FORMULA_FULL_NAME"

      - name: Run brew audit
        run: |
          FORMULA_FULL_NAME="${{ steps.formula_info.outputs.formula_full_name }}"
          echo "Auditing: $FORMULA_FULL_NAME"
          brew audit --online "$FORMULA_FULL_NAME"

      - name: Run brew install and test
        run: |
          FORMULA_FULL_NAME="${{ steps.formula_info.outputs.formula_full_name }}"
          echo "Installing from source: $FORMULA_FULL_NAME"
          brew install --build-from-source "$FORMULA_FULL_NAME"
          echo "Testing formula: $FORMULA_FULL_NAME"
          brew test "$FORMULA_FULL_NAME"
          echo "Uninstalling formula: $FORMULA_FULL_NAME"
          brew uninstall "$FORMULA_FULL_NAME"

      - name: Auto-merge PR
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          echo "Attempting to merge PR #${PR_NUMBER} for branch: ${PR_BRANCH}"
          # Respect checks; do not override protections. Remove --admin.
          gh pr merge "$PR_NUMBER" --squash --delete-branch
          if [ $? -eq 0 ]; then
            echo "Successfully merged PR #${PR_NUMBER} and deleted branch: ${PR_BRANCH}"
          else
            echo "Failed to merge PR #${PR_NUMBER} for branch: ${PR_BRANCH}"
            exit 1
          fi
