---
# Automated formula update workflow
# Runs twice daily to check for upstream releases and create bump PRs
# Uses cleanup mechanism to ensure fresh PRs are created
name: Update Tap

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: update-tap
  cancel-in-progress: true

jobs:
  update-tap:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: true

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global init.defaultBranch main
          git config --global advice.defaultBranchName false

      - name: Cleanup existing bump branches and PRs
        id: cleanup-branches
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Track timing and ensure GitHub API consistency
          START_TIME=$(date +%s)
          echo "start_time=$START_TIME" >> "$GITHUB_OUTPUT"
          echo "Workflow started at: $(date -d "@$START_TIME")"
          echo "Waiting for GitHub API consistency..."
          sleep 5
          echo "Cleaning up existing bump PRs and branches to allow fresh updates..."

      - name: Get existing bump PRs with retry
        id: get-existing-prs
        uses: nick-fields/retry@7152eba30c6575329ac0576536151aca5a72780e # v3.0.0
        with:
          timeout_minutes: 3  # Increased timeout for API calls
          max_attempts: 3
          retry_wait_seconds: 5  # Increased wait time for API consistency
          warning_on_retry: true
          command: |
            EXISTING_PRS=$(gh pr list --state open --json number,headRefName,title | \
              jq -r '.[] | select(.headRefName | startswith("bump-")) | \
                "\(.headRefName): PR #\(.number) - \(.title)"')
            echo "existing_prs=$EXISTING_PRS" >> "$GITHUB_OUTPUT"
            if [[ -n "$EXISTING_PRS" ]]; then
              echo "Found existing bump PRs"
            else
              echo "No existing bump PRs found"
            fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Process existing bump PRs and cleanup
        id: process-cleanup
        env:
          GH_TOKEN: ${{ github.token }}
          EXISTING_PRS: ${{ steps.get-existing-prs.outputs.existing_prs }}
          START_TIME: ${{ steps.cleanup-branches.outputs.start_time }}
        run: |
          set -euo pipefail  # Enable strict error handling

          echo "Processing existing bump PRs..."

          if [[ -n "${EXISTING_PRS:-}" ]]; then
            echo "Found existing bump PRs - closing them to create fresh ones:"
            echo "$EXISTING_PRS"

            # Close existing bump PRs with better error handling
            while IFS= read -r pr_num; do
              if [[ -n "$pr_num" && "$pr_num" =~ ^[0-9]+$ ]]; then
                echo "Closing PR #$pr_num"
                if ! gh pr close "$pr_num" \
                  --comment "Closing to create updated bump PR with latest version"; then
                  echo "⚠️  Warning: Failed to close PR #$pr_num, continuing..."
                fi
              fi
            done < <(gh pr list --state open --json number,headRefName | \
              jq -r '.[] | select(.headRefName | startswith("bump-")) | .number' \
              2>/dev/null || true)

            {
              echo "existing_prs<<EOF"
              echo "$EXISTING_PRS"
              echo "EOF"
              echo "had_existing_prs=true"
              echo "start_time=$START_TIME"
            } >> "$GITHUB_OUTPUT"
          else
            echo "No existing bump PRs found"
            {
              echo "had_existing_prs=false"
              echo "start_time=$START_TIME"
            } >> "$GITHUB_OUTPUT"
          fi

          # Delete ALL bump- branches (both from closed PRs and any orphaned ones)
          BUMP_BRANCHES=$(git ls-remote --heads origin 'bump-*' 2>/dev/null | \
            awk '{print $2}' | sed 's|refs/heads/||' || true)

          if [[ -n "$BUMP_BRANCHES" ]]; then
            echo "Deleting all bump branches to ensure clean state:"
            while IFS= read -r branch; do
              if [[ -n "$branch" ]]; then
                echo "Deleting branch: $branch"
                if ! git push origin --delete "$branch"; then
                  echo "⚠️  Warning: Failed to delete $branch (may not exist), continuing..."
                fi
              fi
            done <<< "$BUMP_BRANCHES"
          else
            echo "No bump branches found to delete"
          fi

          echo "Cleanup complete - ready for fresh bump PRs"
          echo "=== Post-cleanup verification ==="
          echo "Open PRs after cleanup:"
          gh pr list --state open --json number,headRefName,title | \
            jq -r '.[] | select(.headRefName | startswith("bump-")) | \
              "  - PR #\(.number): \(.headRefName)"' \
            2>/dev/null || echo "  No bump PRs found"
          echo "Remote bump branches:"
          git ls-remote --heads origin 'bump-*' 2>/dev/null | \
            awk '{print "  - " $2}' | sed 's|refs/heads/||' || \
            echo "  No bump branches found"
          echo "========================="

      - name: Update Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          livecheck: true
          tap: sheurich/tap
          token: "${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}"
        continue-on-error: true
        id: bump-formula
        env:
          START_TIME: ${{ steps.process-cleanup.outputs.start_time }}

      - name: Summarize updates
        if: always()
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const stepOutcome = '${{ steps.bump-formula.outcome }}';
            const hadExistingPrsStr = '${{ steps.process-cleanup.outputs.had_existing_prs }}';
            const hadExistingPrs = hadExistingPrsStr === 'true';
            const existingPrs = `${{ steps.process-cleanup.outputs.existing_prs }}`;

            core.summary.addHeading('Update Tap Summary');

            if (hadExistingPrs) {
              core.summary.addRaw('🧺 **Cleaned up existing bump PRs:**');
              core.summary.addRaw('\n```');
              core.summary.addRaw('\n' + existingPrs);
              core.summary.addRaw('\n```');
              core.summary.addRaw('\n_These were closed and replaced with fresh bump PRs._\n');
            }

            if (stepOutcome === 'success') {
              core.summary.addRaw('✅ **Formula update completed successfully**');
              if (hadExistingPrs) {
                core.summary.addRaw('\n\n- Closed existing bump PRs and created fresh ones');
                core.summary.addRaw('\n- New PRs contain the latest available versions');
              } else {
                core.summary.addRaw('\n\n- New PRs created for outdated formulae');
                core.summary.addRaw('\n- No action taken if all formulae are up-to-date');
              }
            } else if (stepOutcome === 'failure') {
              core.summary.addRaw('❌ **Formula update failed**');
              core.summary.addRaw('\n\nCommon failure reasons:');
              core.summary.addRaw('\n- Network or API connectivity issues');
              core.summary.addRaw('\n- Formula syntax or validation errors');
              core.summary.addRaw('\n- GitHub API rate limits');
              core.summary.addRaw('\n- Upstream source changes requiring manual intervention');
              if (hadExistingPrs) {
                core.summary.addRaw('\n\n_Note: Existing bump PRs were closed ' +
                  'before this attempt._');
              }
            } else {
              core.summary.addRaw('ℹ️ Formula update was skipped or cancelled.');
            }

            await core.summary.write();
