name: Update Tap

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: read
  pull-requests: write

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}

      - name: Update Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@v3
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        with:
          livecheck: true
          tap: sheurich/tap
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
