---
name: Update Tap

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: update-tap
  cancel-in-progress: true

jobs:
  update-tap:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          livecheck: true
          tap: sheurich/tap
          token: "${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}"
        continue-on-error: true
        id: bump-formula

      - name: Handle bump results
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const stepOutcome = '${{ steps.bump-formula.outcome }}';
            
            core.summary.addHeading('Update Tap Summary');
            
            if (stepOutcome === 'success') {
              core.summary.addRaw('✅ Formula bump completed successfully. New PRs may have been opened.');
            } else if (stepOutcome === 'failure') {
              core.summary.addRaw('⚠️  Formula bump encountered issues (likely duplicate PRs or no updates available). Check the logs for details.');
              core.summary.addRaw('\n\nCommon reasons for failure:');
              core.summary.addRaw('\n- Duplicate PRs already exist for the latest versions');
              core.summary.addRaw('\n- No new versions available upstream');
              core.summary.addRaw('\n- Temporary network or API issues');
            } else {
              core.summary.addRaw('ℹ️ Formula bump was skipped or cancelled.');
            }
            
            await core.summary.write();

