name: Update Tap

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tap: sheurich/tap
          livecheck: true
