---
name: Update Tap

"on":
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: update-tap
  cancel-in-progress: true

jobs:
  update-tap:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Configure Git for signed commits
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global commit.gpgsign true
          git config --global tag.gpgSign true
          git config --global gpg.format ssh
          git config --global user.signingkey "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"

      - name: Update Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@v4
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        with:
          livecheck: true
          tap: sheurich/tap
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Summarize updates
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            core.summary.addHeading('Update Tap Summary')
            core.summary.addRaw('If updates were found, bump PRs have been opened automatically.')
            await core.summary.write()
