---
name: Validate Bump PR

'on':
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  validate:
    if: startsWith(github.head_ref, 'bump-')
    runs-on: macos-latest
    name: Formula Validation
    steps:
      - uses: actions/checkout@v5

      - uses: Homebrew/actions/setup-homebrew@main

      - name: Enable auto-merge
        if: github.event.action == 'opened'
        run: |
          PR_NUM=${{ github.event.pull_request.number }}
          echo "Enabling auto-merge for PR #$PR_NUM"
          gh pr merge $PR_NUM \
            --repo ${{ github.repository }} \
            --auto --squash --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run test-bot validation
        run: |
          # Comprehensive formula testing
          # Includes: audit, style, install, and test
          brew test-bot --tap=${{ github.repository }}
